<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Regression suite1" duration-ms="76" started-at="2020-07-10T13:20:07Z" finished-at="2020-07-10T13:20:07Z">
    <groups>
    </groups>
    <test name="Program Test on FF" duration-ms="33" started-at="2020-07-10T13:20:07Z" finished-at="2020-07-10T13:20:07Z">
      <class name="com.automationpratice.pageclasses.homepage.home.Testing">
        <test-method status="FAIL" signature="loginScreen(java.lang.String, java.lang.String)[pri:0, instance:com.automationpratice.pageclasses.homepage.home.Testing@bd8db5a]" name="loginScreen" duration-ms="11" started-at="2020-07-10T13:20:07Z" finished-at="2020-07-10T13:20:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ch]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.monsterindia.com/]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.automationpratice.pageclasses.homepage.home.Testing.loginScreen(Testing.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginScreen -->
      </class> <!-- com.automationpratice.pageclasses.homepage.home.Testing -->
    </test> <!-- Program Test on FF -->
    <test name="Program Test on IE" duration-ms="5" started-at="2020-07-10T13:20:07Z" finished-at="2020-07-10T13:20:07Z">
      <class name="com.automationpratice.pageclasses.homepage.home.Testing">
        <test-method status="FAIL" signature="loginScreen(java.lang.String, java.lang.String)[pri:0, instance:com.automationpratice.pageclasses.homepage.home.Testing@687080dc]" name="loginScreen" duration-ms="2" started-at="2020-07-10T13:20:07Z" finished-at="2020-07-10T13:20:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ie]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.monsterindia.com/]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.automationpratice.pageclasses.homepage.home.Testing.loginScreen(Testing.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginScreen -->
      </class> <!-- com.automationpratice.pageclasses.homepage.home.Testing -->
    </test> <!-- Program Test on IE -->
  </suite> <!-- Regression suite1 -->
</testng-results>
